#import turtle
# turtle.forward(120)
# turtle.right(120)
# turtle.forward(120)
# turtle.right(120)
# turtle.forward(120)
# turtle.right(120)
#turtle.forward(135)
#turtle.right(135)
#turtle.forward(135)
#turtle.left(135)
#turtle.forward(135)
# turtle.right(90)
# turtle.fd(200)
# turtle.bk(100)
# turtle.left(90)
# turtle.fd(90)
# turtle.right(90)
# turtle.fd(100)
# turtle.bk(200)
#turtle.goto(123,123)
from turtle import *
speed(0)
up()
bk(200)
down()
pencolor("red")
fillcolor("blue")
begin_fill()
circle(150)
end_fill()
pencolor("yellow")
fillcolor("red")
begin_fill()
circle(100)
end_fill()
pencolor("cyan")
fillcolor("green")
begin_fill()
circle(50)
end_fill()
up()
fd(400)
down()
pencolor("red")
fillcolor("blue")
begin_fill()
circle(150)
end_fill()
pencolor("yellow")
fillcolor("red")
begin_fill()
circle(100)
end_fill()
pencolor("cyan")
fillcolor("green")
begin_fill()
circle(50)
end_fill()
up()
right(90)
fd(100)
right(90)
fd(300)
pencolor("red")
pensize(30)
down()
circle(-100,50)
done()

